# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:30
from __future__ import unicode_literals

from django.db import migrations

_prefix = 'eventary'
_groups = ['management', 'editorial']


def forwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create([
        Group(name='{prefix}_{group_name}'.format(
            prefix=_prefix,
            group_name=group
        ))
        for group in _groups
    ])


def backwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(
        name__in=[
            '{prefix}_{group_name}'.format(
                prefix=_prefix,
                group_name=group
            )
            for group in _groups
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [("eventary", "0001_initial")]
    operations = [migrations.RunPython(forwards, backwards)]
