# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('eventary', '0004_change_timedate_relation_to_one_to_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                                          verbose_name='host name')),
                ('info', models.CharField(blank=True,
                                          max_length=50,
                                          null=True,
                                          verbose_name='info')),
                ('phone', models.CharField(max_length=20,
                                           verbose_name='tel. Kontakt')),
                ('email', models.EmailField(blank=True,
                                            max_length=254,
                                            null=True,
                                            verbose_name='email')),
                ('homepage', models.URLField(blank=True,
                                             null=True,
                                             verbose_name='Homepage')),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='eventary.EventHost',
                verbose_name='Veranstalter'
            ),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
