# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0005_event_host_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventary.Event', verbose_name='Veranstaltung')),
            ],
        ),
    ]
