# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import eventary.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0006_eventrecurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Veranstalter'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telefonischer Kontakt'),
        ),
    ]
