# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import eventary.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0007_change_max_length_of_image_and_document_field_to_255'),
    ]

    operations = [
        # see http://stackoverflow.com/questions/28429933/django-migrations-using-runpython-to-commit-changes
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='eventhost',
            name='notify',
            field=models.BooleanField(default=True, help_text='do you want to receive an email when your event has been published, hidden or updated?', verbose_name='activate email notifications'),
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Dammweg 9', help_text='address & nr.', max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Bern', max_length=255, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.TextField(blank=True, null=True, verbose_name='entry_fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.CharField(default='3013', max_length=255, verbose_name='ZIP code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, help_text='accepted formats: pdf, jpg, png', max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(blank=True, help_text='http://...', null=True, verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='accepted formats: jpg, png', max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='4teamwork', help_text="ex. Wendy's", max_length=255, verbose_name='Veranstaltungsort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(verbose_name='Publiziert'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=False, help_text='is your event a recurring event?', verbose_name='recurring'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='email',
            field=models.EmailField(default='info@4teamwork.ch', max_length=254, verbose_name='E-Mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='info',
            field=models.CharField(blank=True, help_text='todo: this info field requires a helptext', max_length=50, null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='phone',
            field=models.CharField(help_text="this field is displayed in the events' details", max_length=20, verbose_name='telefonischer Kontakt'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='prize',
        ),
        # see http://stackoverflow.com/questions/28429933/django-migrations-using-runpython-to-commit-changes
        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE')
    ]
