# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:00
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import eventary.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0008_improve_models_for_#68_#124_#118_#116_#115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='view_limit',
            field=models.IntegerField(help_text='limits the number of daily anonymous views for proposed events', verbose_name='view limit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventary.Calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(blank=True, help_text='comment', max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, help_text='accepted formats: pdf, jpg, png', max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.TextField(blank=True, null=True, verbose_name='entry fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(blank=True, help_text='http://...', null=True, verbose_name='homepage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventary.EventHost', verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='accepted formats: jpg, png', max_length=255, null=True, upload_to=eventary.models._get_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text="ex. Wendy's", max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='homepage'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='info',
            field=models.CharField(blank=True, help_text='todo: this info field requires a helptext', max_length=50, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='name',
            field=models.CharField(max_length=50, verbose_name='host name'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='phone',
            field=models.CharField(help_text="this field is displayed in the events' details", max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='eventrecurrence',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventary.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='comment',
            field=models.CharField(blank=True, help_text='comment', max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='end_date',
            field=models.DateField(blank=True, help_text='end date', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='end_time',
            field=models.TimeField(blank=True, help_text='end time', null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventary.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='start_date',
            field=models.DateField(help_text='start date', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eventtimedate',
            name='start_time',
            field=models.TimeField(blank=True, help_text='start time', null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(blank=True, to='eventary.Event', verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventary.Grouping', verbose_name='grouping'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='calendars',
            field=models.ManyToManyField(blank=True, to='eventary.Calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='grouping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventary.GroupingType', verbose_name='grouping type'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='groupingtype',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='calls',
            field=models.IntegerField(default=0, verbose_name='calls'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventary.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='last_call',
            field=models.DateField(null=True, verbose_name='last call'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='secret'),
        ),
    ]
