# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0009_ugettext_ugettext_lazy_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedEvent',
            fields=[
                ('importuid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventary.Event', verbose_name='linked event')),
            ],
        ),
    ]
