# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0010_importedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhost',
            name='homepage',
            field=models.URLField(blank=True, help_text='http://...', null=True, verbose_name='homepage'),
        ),
    ]
