# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0011_event_homepage_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='info',
        ),
        migrations.RemoveField(
            model_name='eventtimedate',
            name='comment',
        ),
    ]
