# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import eventary.models.base
import eventary.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0012_remove_comment_and_info_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, help_text='accepted formats: pdf, jpg, png', max_length=255, null=True, upload_to=eventary.models.base._get_upload_path, validators=[eventary.validators.validate_file_extension], verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='accepted formats: jpg, png', max_length=255, null=True, upload_to=eventary.models.base._get_upload_path, validators=[eventary.validators.validate_image_extension], verbose_name='image'),
        ),
    ]
