# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0013_add_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='filter_time_span',
            field=models.DurationField(default=datetime.timedelta(7), help_text='configure the default search form time span filter', verbose_name='default time span filter'),
        ),
    ]
