# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0014_calendar_filter_time_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='notify_on_submission',
            field=models.TextField(blank=True, default='', help_text='email addresses to notify on new submissions', verbose_name='notified via email'),
        ),
    ]
