# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0015_calendar_notify_on_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='allow_anonymous_event_proposals',
            field=models.BooleanField(default=False, help_text='allow anonymous users to propose events', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='notify_on_submission',
            field=models.TextField(blank=True, default='', help_text='email addresses to notify on new event submissions', verbose_name='notified via email'),
        ),
    ]
