# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0017_add_timestamps_for_mutations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouping',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='grouping',
            name='order',
            field=models.IntegerField(default=0, help_text='Used to order the filter form fields. Needs a restart of the application.', verbose_name='Order'),
        ),
    ]
