# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventary', '0018_order_the_grooupings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='homepage_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titel der Homepage'),
        ),
    ]
